### ISSUE TITLE
Import error with decode_dss_signature

### ISSUE THREAD

**Issue by bugzapperini** [mwrlabs/needle#10]
Followed everything written in guide and installed all the packages on Kali 2.0. But facing following error. Tried forceful installation of paramiko as well.

Import error
# python needle.py 
Traceback (most recent call last):
  File "needle.py", line 9, in <module>
    from core.framework import cli
  File "/root/needle/needle/core/framework/cli.py", line 9, in <module>
    from framework import Framework, FrameworkException
  File "/root/needle/needle/core/framework/framework.py", line 9, in <module>
    from ..device.device import Device
  File "/root/needle/needle/core/device/device.py", line 2, in <module>
    import paramiko
  File "/usr/local/lib/python2.7/dist-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 53, in <module>
    from paramiko.dsskey import DSSKey
  File "/usr/local/lib/python2.7/dist-packages/paramiko/dsskey.py", line 27, in <module>
    from cryptography.hazmat.primitives.asymmetric.utils import (
ImportError: cannot import name decode_dss_signature

**Comment by marco-lancini** [comment]
Hi, did you managed to successfully install paramiko then? Or the installation fails at some point?

**Comment by bugzapperini** [comment]
It didn't fail. However before installing all the python modules, I upgraded Kali 2.0. Does that affect paramiko in anyway? If yes, then I'll freshly start the installation.

**Comment by marco-lancini** [comment]
Unfortunately we don't mantain/troubleshoot paramiko.
Try to install it from scratch and in a python shell test if the following works fine:

`from paramiko.dsskey import DSSKey`

**Comment by bugzapperini** [comment]
Sure will do that. Thanks for response.
