### ISSUE TITLE
unable to get class-dump of application.

### ISSUE THREAD

**Issue by kryptoknight13** [mwrlabs/needle#107]
## Issue
not able to get class-dump 

### Expected behaviour
should be able to view class-dump for application selected after "run".

### Actual behaviour

```
[needle] > use binary/class_dump
[needle][class_dump] > run
[*] Checking connection with device...
[+] Already connected to: localhost
[V] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[*] Target app not selected. Launching wizard...
[D] [REMOTE CMD] Remote Command: if [ -f /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist ]; then echo "yes"; else echo "no" ; fi
[V] Refreshing list of installed apps...
[D] [REMOTE CMD] Remote Command: /bin/su mobile -c /usr/bin/uicache
[D] Copy the plist to temp: /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist -> /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: cp /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist /var/root/needle/LastLaunchServicesMap.plist
[D] Converting plist to XML: /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/LastLaunchServicesMap.plist
[D] Extracting content from: /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/LastLaunchServicesMap.plist
[D] Parsing plist content
[+] Apps found:
		0 - com.legalrobot
		1 - com.burbn.instagram
		2 - com.innerfour.photovault
		3 - com.catchhq.yovople
		4 - com.accenture.mobility.appfactory.dev.SCSampleApp2
		5 - com.jadedpixel.shopify
		6 - com.accenture.ams.dev.acssp
		7 - com.circle.CircleApp
		8 - com.cisco.anyconnect.gui
		9 - com.zaption.ZaptionViewer
		10 - com.accenture.mobility.appfactory.dev.GDB
		11 - com.ideashower.ReadItLaterPro
		12 - com.atebits.Tweetie2
		13 - com.bms.who
		14 - com.none.smartplug
		15 - com.highaltitudehacks.dvia
		16 - com.lenovo.anyshare
		17 - com.tinyspeck.chatlyio
		18 - com.zopim.iphone
		19 - com.node.push04115
		20 - accenture.Crowd-Test-App
		21 - com.yahoo.weather
		22 - com.TapMediaLtd.QRReader
		23 - com.accenture.MeuTim
[>][QUESTION] Please select a number: 0
[+] Target app: com.legalrobot
[*] Retrieving app's metadata...
[D] Copy the plist to temp: '/private/var/mobile/Containers/Bundle/Application/AF4E1FBC-980B-4D56-9F44-96DDF391BF5E/Legal Robot.app/Info.plist' -> /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cp '/private/var/mobile/Containers/Bundle/Application/AF4E1FBC-980B-4D56-9F44-96DDF391BF5E/Legal Robot.app/Info.plist' /var/root/needle/Info.plist
[D] Converting plist to XML: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/Info.plist
[D] Extracting content from: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/Info.plist
[D] Parsing plist content
[D] [REMOTE CMD] Remote Command: lipo -info '/private/var/mobile/Containers/Bundle/Application/AF4E1FBC-980B-4D56-9F44-96DDF391BF5E/Legal Robot.app/Legal Robot'
[D] [REMOTE CMD] Remote Command: if [ -d '/private/var/mobile/Containers/Bundle/Application/AF4E1FBC-980B-4D56-9F44-96DDF391BF5E/Legal Robot.app/PlugIns' ]; then echo "yes"; else echo "no" ; fi
[*] Decrypting the binary...
[D] [REMOTE CMD] Remote Command: Clutch2 -d com.legalrobot 2>&1
[D] [REMOTE CMD] Remote Command: cp '/private/var/mobile/Documents/Dumped/com.legalrobot-iOS9.0-(Clutch-2.0.2).ipa' /var/root/needle/decrypted.ipa
[D] [REMOTE CMD] Remote Command: if [ -f '/private/var/mobile/Documents/Dumped/com.legalrobot-iOS9.0-(Clutch-2.0.2).ipa' ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: rm '/private/var/mobile/Documents/Dumped/com.legalrobot-iOS9.0-(Clutch-2.0.2).ipa' 2> /dev/null
[V] Decrypted IPA stored at: /var/root/needle/decrypted.ipa
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/Payload ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/Payload ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: rm -rf /var/root/needle/Payload 2> /dev/null
[D] [REMOTE CMD] Remote Command: if [ -f /var/root/needle/iTunesArtwork ]; then echo "yes"; else echo "no" ; fi
[*] Unpacking the IPA...
[D] [REMOTE CMD] Remote Command: unzip /var/root/needle/decrypted.ipa -d /var/root/needle/
[D] [REMOTE CMD] Remote Command: find /var/root/needle/ -type f -name "Legal Robot"
[D] Full path of the application binary: /var/root/needle/Payload/Legal Robot.app/Legal Robot
[*] Dumping classes...
[D] [REMOTE CMD] Remote Command: class-dump "/var/root/needle/Payload/Legal Robot.app/Legal Robot" 2>/dev/null
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/akanksha.bana/Desktop/needle/needle/core/framework/module.py", line 118, in do_run
    self.module_run()
  File "/Users/akanksha.bana/Desktop/needle/needle/modules/binary/class_dump.py", line 69, in module_run
    self.class_dump()
  File "/Users/akanksha.bana/Desktop/needle/needle/modules/binary/class_dump.py", line 51, in class_dump
    out = self.device.remote_op.command_blocking(cmd)
  File "/Users/akanksha.bana/Desktop/needle/needle/core/device/remote_operations.py", line 93, in command_blocking
    out, err = self._device._exec_command_ssh(cmd, internal)
  File "/Users/akanksha.bana/Desktop/needle/needle/core/device/device.py", line 123, in _exec_command_ssh
    raise Exception(err_str)
Exception: sh: line 1:   984 Segmentation fault: 11  class-dump "/var/root/needle/Payload/Legal Robot.app/Legal Robot" 2> /dev/null

------------------------------------------------------------
[!] Exception: sh: line 1:   984 Segmentation fault: 11  class-dump "/var/root/needle/Payload/Legal Robot.app/Legal Robot" 2> /dev/null.
[needle][class_dump] >

```

### Steps to reproduce
1. show modules
2. use binary/class_dump
3. run
4. selecting "0" for Legal Robot application (https://itunes.apple.com/us/app/legal-robot/id1072408741?mt=8)

### needle error logs
Ensure verbose and debug mode are enabled:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

#### Workstation Operating System
OSX 10.11.6

#### Python Version
Python 2.7.10

#### Python Packages (`pip freeze`)
pip

#### Device iOS Version
9.1

**Comment by kryptoknight13** [comment]
i understand the limitation, however my concern is different. 
Can we show a proper message stating that binary is encrypted and class-dump is not accessible instead of throwing unwanted error?

**Comment by smhome** [comment]
Hi @marco-lancini,
I have a question in this context: I am getting the same error ("Segmentation fault: 11"). Is this because the target app is composed of mixed obj-c and swift?
