### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _map_fd

### ISSUE THREAD

**Issue by jithin005** [mwrlabs/needle#11]
I selected binary/class_dump, run the module but it gives error

```
Exception: dyld: lazy symbol binding failed: Symbol not found: _map_fd
  Referenced from: /usr/bin/lipo
  Expected in: dyld shared cache

dyld: Symbol not found: _map_fd
  Referenced from: /usr/bin/lipo
  Expected in: dyld shared cache
```

also there is an error:
`Prerequisite Not Found: apt-get .`

But i have installed apt 0.7 strict

**Comment by marco-lancini** [comment]
Hi, I've you tried to clone the more recent version?

**Comment by jithin005** [comment]
I dont think so. Is the both error due to old version?

**Comment by marco-lancini** [comment]
Can you please clone Needle now, and try again?

**Comment by jithin005** [comment]
Same error is coming.

**Comment by marco-lancini** [comment]
can you please enable verbose (`set VERBOSE True`) and debug (`set DEBUG True`) logging, and pasting the output?

**Comment by jithin005** [comment]
`[needle][metadata] > run
[*] Checking connection with device...
[V] Connection not present, creating a new instance
[V] Setting up USB port forwarding on port 2222
[D] [LOCAL CMD] Local Subprocess Command: /home/shawn/Downloads/needle-master/needle/libs/usbmuxd/tcprelay.py -t 22:2222
[V] Setting up SSH connection...
[+] Connected to: 127.0.0.1
[V] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: mkdir /var/root/needle/
[*] Configuring device...
[D] [REMOTE CMD] Remote Command: which apt-get
[!] Prerequisite Not Found: apt-get .
[!] Please install the requirements listed in the README file.
[*] Target app not selected. Launching wizard...
[D] [REMOTE CMD] Remote Command: if [ -f /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist ]; then echo "yes"; else echo "no" ; fi
[V] Refreshing list of installed apps...
[D] [REMOTE CMD] Remote Command: /bin/su mobile -c /usr/bin/uicache
[D] [REMOTE CMD] Remote Command: cp /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/LastLaunchServicesMap.plist
[+] Apps found:
		0 - cn.a.b.b
		1 - com.a.c
Please select a number: 0
[+] Target app: cn.a.b.b
[*] Retrieving app's metadata...
[D] [REMOTE CMD] Remote Command: cp /private/var/mobile/Containers/Bundle/Application/524E8614-8288-4001-B591-7830FC752538/abc.app/Info.plist /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: lipo -info /private/var/mobile/Containers/Bundle/Application/524E8614-8288-4001-B591-7830FC752538/abc.app/abc
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shawn/Downloads/needle-master/needle/core/framework/module.py", line 111, in do_run
    pre = self.module_pre()
  File "/home/shawn/Downloads/needle-master/needle/core/framework/module.py", line 135, in module_pre
    if self.app_check() is None: return None
  File "/home/shawn/Downloads/needle-master/needle/core/framework/framework.py", line 677, in app_check
    self.APP_METADATA = Framework.APP_METADATA = self.device.app.get_metadata(app)
  File "/home/shawn/Downloads/needle-master/needle/core/device/app.py", line 20, in get_metadata
    return self._retrieve_metadata()
  File "/home/shawn/Downloads/needle-master/needle/core/device/app.py", line 57, in _retrieve_metadata
    architectures = self._detect_architectures(binary_path)
  File "/home/shawn/Downloads/needle-master/needle/core/device/app.py", line 83, in _detect_architectures
    out = self._device.remote_op.command_blocking(cmd, internal=True)
  File "/home/shawn/Downloads/needle-master/needle/core/device/remote_operations.py", line 84, in command_blocking
    out, err = self._device._exec_command_ssh(cmd, internal)
  File "/home/shawn/Downloads/needle-master/needle/core/device/device.py", line 118, in _exec_command_ssh
    raise Exception(err_str)
Exception: dyld: lazy symbol binding failed: Symbol not found: _map_fd
  Referenced from: /usr/bin/lipo
  Expected in: dyld shared cache

dyld: Symbol not found: _map_fd
  Referenced from: /usr/bin/lipo
  Expected in: dyld shared cache


------------------------------------------------------------
[!]   Expected in: dyld shared cache.
`

**Comment by marco-lancini** [comment]
Ok, thanks for the log. Can you confirm that `apt` is definitely installed?
You can test for it by SSH into the device and for example try to `apt-get update`

**Comment by jithin005** [comment]
apt-get update is working fine

**Comment by jithin005** [comment]
any fix for this issue??

**Comment by marco-lancini** [comment]
Hi @jithin005, we are still unable to reproduce this issue.
Have you tried to install lipo manually form Cydia? 
It should be contained in the "_Darwin CC Tools_" package (`org.coolstar.cctools`)

**Comment by jithin005** [comment]
Can @marco-lancini help me on installing it? I have installed darwin cc tools using cydia.

**Comment by jithin005** [comment]
Error update: now showing `UnicodeDecodeError: 'utf8' codec can't decode byte 0xd5 in position 60: invalid continuation byte`

and my ap-get is working fine but still it shows apt-get not found.

**Comment by jithin005** [comment]
the full traceback of the above error

```
Traceback (most recent call last):
  File "/home/shawn/needle-master/needle/core/framework/module.py", line 114, in do_run
    self.module_run()
  File "/home/shawn/needle-master/needle/modules/binary/strings.py", line 45, in module_run
    self.fname_binary = self.device.app.decrypt(self.APP_METADATA)
  File "/home/shawn/needle-master/needle/core/device/app.py", line 148, in decrypt
    out = self._device.remote_op.command_blocking(cmd)
  File "/home/shawn/needle-master/needle/core/device/remote_operations.py", line 84, in command_blocking
    out, err = self._device._exec_command_ssh(cmd, internal)
  File "/home/shawn/needle-master/needle/core/device/device.py", line 113, in _exec_command_ssh
    out = stdout.readlines()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/file.py", line 327, in readlines
    line = self.readline()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/file.py", line 312, in readline
    return line if self._flags & self.FLAG_BINARY else u(line)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/py3compat.py", line 53, in u
    return s.decode(encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd5 in position 60: invalid continuation byte

```

**Comment by marco-lancini** [comment]
Can you please provide the full log, from when you start Needle up to this error? 
(for example. I would like to see what application you are targeting)

**Comment by jithin005** [comment]
is this error application specific?? let me check

**Comment by jithin005** [comment]
the error is not application specific. it is showing the same error in all apps.

**Comment by jithin005** [comment]
not showing apps installed using cydia y?

**Comment by marco-lancini** [comment]
@jithin005 Can you please provide the full log, from when you start Needle up to this error? 
(for example. I would like to see what application you are targeting)

**Comment by jithin005** [comment]
Since the app that i am testing is confidential I cant say the name of it . 


```

[needle] > use binary/strings
[needle][strings] > run
[*] Checking connection with device...
[+] Already connected to: 127.0.0.1
[V] Creating temp folder: /var/root/needle/
[*] Configuring device...
[!] Prerequisite Not Found: apt-get .
[!] Please install the requirements listed in the README file.
[+] Target app: cn.abb.com.ijiapush
[*] Retrieving app's metadata...
[*] Decrypting the binary...
[?] The app might be already decrypted. Trying to retrieve the IPA...
[V] Decrypted IPA stored at: /var/root/needle/decrypted.ipa
[*] Unpacking the decrypted IPA...
[!] UnicodeDecodeError: 'utf8' codec can't decode byte 0xd5 in position 60: invalid continuation byte.

```

**Comment by jithin005** [comment]
```
[needle] > use binary/strings
[needle][strings] > run
[*] Checking connection with device...
[+] Already connected to: 127.0.0.1
[V] Creating temp folder: /var/root/needle/
[*] Configuring device...
[!] Prerequisite Not Found: apt-get .
[!] Please install the requirements listed in the README file.
[+] Target app: a.b.c.d
[*] Retrieving app's metadata...
[*] Decrypting the binary...
[?] The app might be already decrypted. Trying to retrieve the IPA...
[V] Decrypted IPA stored at: /var/root/needle/decrypted.ipa
[*] Unpacking the decrypted IPA...
[!] UnicodeDecodeError: 'utf8' codec can't decode byte 0xd5 in position 60: invalid continuation byte.

```

**Comment by marco-lancini** [comment]
is `a.b.c.d` the real bundle id, or you redacted it?
also, debug mode was not enabled in the dump you provided

**Comment by jithin005** [comment]
yes i changed it.

**Comment by jithin005** [comment]
```
[needle] > set DEBUG true
DEBUG => true
[needle] > use binary/strings
[needle][strings] > run
[*] Checking connection with device...
[V] Connection not present, creating a new instance
[V] Setting up USB port forwarding on port 2222
[D] [LOCAL CMD] Local Subprocess Command: /home/shawn/needle-master/needle/libs/usbmuxd/tcprelay.py -t 22:2222
[V] Setting up SSH connection...
[+] Connected to: 127.0.0.1
[V] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[*] Configuring device...
[D] [REMOTE CMD] Remote Command: which apt-get
[!] Prerequisite Not Found: apt-get .
[!] Please install the requirements listed in the README file.
[*] Target app not selected. Launching wizard...
[D] [REMOTE CMD] Remote Command: if [ -f /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist ]; then echo "yes"; else echo "no" ; fi
[V] Refreshing list of installed apps...
[D] [REMOTE CMD] Remote Command: /bin/su mobile -c /usr/bin/uicache
[D] [REMOTE CMD] Remote Command: cp /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/LastLaunchServicesMap.plist
[+] Apps found:
		0 - a.b.c.d
		1 - e.f.g.h
Please select a number: 0
[+] Target app: a.b.c.d
[*] Retrieving app's metadata...
[D] [REMOTE CMD] Remote Command: cp /private/var/mobile/Containers/Bundle/Application/524E8614-8288-4001-B591-7830FC752538/abc.app/Info.plist /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: lipo -info /private/var/mobile/Containers/Bundle/Application/524E8614-8288-4001-B591-7830FC752538/abc.app/abc
[*] Decrypting the binary...
[D] [REMOTE CMD] Remote Command: Clutch2 -d a.b.c.d 2>&1
[?] The app might be already decrypted. Trying to retrieve the IPA...
[D] [REMOTE CMD] Remote Command: ipainstaller -b a.b.c.d -o /var/root/needle/decrypted.ipa
[V] Decrypted IPA stored at: /var/root/needle/decrypted.ipa
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/Payload ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/Payload ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: rm -rf /var/root/needle/Payload 2> /dev/null
[D] [REMOTE CMD] Remote Command: if [ -f /var/root/needle/iTunesArtwork ]; then echo "yes"; else echo "no" ; fi
[*] Unpacking the decrypted IPA...
[D] [REMOTE CMD] Remote Command: unzip /var/root/needle/decrypted.ipa -d /var/root/needle/
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shawn/needle-master/needle/core/framework/module.py", line 114, in do_run
    self.module_run()
  File "/home/shawn/needle-master/needle/modules/binary/strings.py", line 45, in module_run
    self.fname_binary = self.device.app.decrypt(self.APP_METADATA)
  File "/home/shawn/needle-master/needle/core/device/app.py", line 148, in decrypt
    out = self._device.remote_op.command_blocking(cmd)
  File "/home/shawn/needle-master/needle/core/device/remote_operations.py", line 84, in command_blocking
    out, err = self._device._exec_command_ssh(cmd, internal)
  File "/home/shawn/needle-master/needle/core/device/device.py", line 113, in _exec_command_ssh
    out = stdout.readlines()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/file.py", line 327, in readlines
    line = self.readline()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/file.py", line 312, in readline
    return line if self._flags & self.FLAG_BINARY else u(line)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/py3compat.py", line 53, in u
    return s.decode(encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd5 in position 60: invalid continuation byte
------------------------------------------------------------
[!] UnicodeDecodeError: 'utf8' codec can't decode byte 0xd5 in position 60: invalid continuation byte.
```

**Comment by jithin005** [comment]
Any fix for this issue???

**Comment by marco-lancini** [comment]
@jithin005 as said previously, I can't troubleshoot this if you don't provide me the real bundle id that is causing the issue

**Comment by jithin005** [comment]
All apps show the same error.
```
[needle] > use binary/strings
[needle][strings] > run
[*] Checking connection with device...
[+] Already connected to: 127.0.0.1
[V] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[+] Target app: awesomevibescrew.blockpuzzle.fillmein
[*] Decrypting the binary...
[D] [REMOTE CMD] Remote Command: Clutch2 -d awesomevibescrew.blockpuzzle.fillmein 2>&1
[?] The app might be already decrypted. Trying to retrieve the IPA...
[D] [REMOTE CMD] Remote Command: ipainstaller -b awesomevibescrew.blockpuzzle.fillmein -o /var/root/needle/decrypted.ipa
[V] Decrypted IPA stored at: /var/root/needle/decrypted.ipa
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/Payload ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/Payload ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: rm -rf /var/root/needle/Payload 2> /dev/null
[D] [REMOTE CMD] Remote Command: if [ -f /var/root/needle/iTunesArtwork ]; then echo "yes"; else echo "no" ; fi
[*] Unpacking the decrypted IPA...
[D] [REMOTE CMD] Remote Command: unzip /var/root/needle/decrypted.ipa -d /var/root/needle/
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shawn/needle-master/needle/core/framework/module.py", line 114, in do_run
    self.module_run()
  File "/home/shawn/needle-master/needle/modules/binary/strings.py", line 45, in module_run
    self.fname_binary = self.device.app.decrypt(self.APP_METADATA)
  File "/home/shawn/needle-master/needle/core/device/app.py", line 215, in decrypt
    out = self._device.remote_op.command_blocking(cmd)
  File "/home/shawn/needle-master/needle/core/device/remote_operations.py", line 88, in command_blocking
    out, err = self._device._exec_command_ssh(cmd, internal)
  File "/home/shawn/needle-master/needle/core/device/device.py", line 113, in _exec_command_ssh
    out = stdout.readlines()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/file.py", line 327, in readlines
    line = self.readline()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/file.py", line 312, in readline
    return line if self._flags & self.FLAG_BINARY else u(line)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/py3compat.py", line 53, in u
    return s.decode(encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd5 in position 60: invalid continuation byte
------------------------------------------------------------
[!] UnicodeDecodeError: 'utf8' codec can't decode byte 0xd5 in position 60: invalid continuation byte.

```

**Comment by flamecopper** [comment]
Yes, I confirm this issue was resolved after installing coolstar package from darwin cc tools.
