### ISSUE TITLE
SCP is not installed by default in Yalu jailbreaks - breaking modules needing this on the device.

### ISSUE THREAD

**Issue by peterfillmore** [mwrlabs/needle#136]
## Issue
SCP is not included in the dependencies on the device side.
This pops up when using the Yalu102 jailbreak as this uses Dropbear - and installing OpenSSH on a device with Yalu breaks ssh.

### needle error logs
~~~~
[LOCAL CMD] Local Command: sshpass -p "alpine" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 4642 root@192.168.1.2:"/private/var/containers/Bundle/Application/<the app>/Info.plist" /root/.needle/tmp/plist
------------------------------------------------------------
Traceback (most recent call last):
  File "/root/src/needle/needle/core/framework/module.py", line 111, in do_run
    pre = self.module_pre()
  File "/root/src/needle/needle/core/framework/module.py", line 147, in module_pre
    if self.app_check() is None: return None
  File "/root/src/needle/needle/core/framework/framework.py", line 665, in app_check
    self.APP_METADATA = Framework.APP_METADATA = self.device.app.get_metadata(app)
  File "/root/src/needle/needle/core/device/app.py", line 19, in get_metadata
    return self._retrieve_metadata()
  File "/root/src/needle/needle/core/device/app.py", line 31, in _retrieve_metadata
    plist_info = self._device.remote_op.parse_plist(plist_info_path)
  File "/root/src/needle/needle/core/device/remote_operations.py", line 219, in parse_plist
    content = Utils.plist_read_from_file(plist_copy)
  File "/root/src/needle/needle/core/utils/utils.py", line 149, in plist_read_from_file
    plist = biplist.readPlist(path)
  File "/usr/local/lib/python2.7/dist-packages/biplist/__init__.py", line 122, in readPlist
    pathOrFile = open(pathOrFile, 'rb')
IOError: [Errno 2] No such file or directory: '/root/.needle/tmp/plist'
------------------------------------------------------------
[!] IOError: [Errno 2] No such file or directory: '/root/.needle/tmp/plist'.
~~~~

#### Device iOS Version
iOS 10.0.2 jailbroken with yalu.

###Fix
add a dependency link to http://newosxbook.com/tools/iOSBinaries.html
and install the most recent tools.

**Comment by marco-lancini** [comment]
Hi @peterfillmore, `scp` is already included as a dependency. It will be automatically installed on the device if you set `SETUP_DEVICE` to `True`
