### ISSUE TITLE
Error Dyld

### ISSUE THREAD

**Issue by c0d3xpl0it** [mwrlabs/needle#149]
Hello,

I am new to Needle and faced error show below while using these 2 modules.

```
[needle] > use binary/info/metadata
[needle][metadata] > use binary/reversing/strings
```

Error: 
```
[needle][strings] > run
[*] Checking connection with device...
[+] Already connected to: 192.168.100.11
[D] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[+] Target app: com.mytechnologies.ownme
[*] Retrieving app's metadata...
/private/var/mobile/Containers/Bundle/Application/57C5310C-57F7-4583-BC16-0FEA2F5613A6/MCEirectTest.app/Info.plist
[D] Copying the plist to temp: /private/var/mobile/Containers/Bundle/Application/57C5310C-57F7-4583-BC16-0FEA2F5613A6/MCEirectTest.app/Info.plist -> /root/.needle/tmp/plist
[*] Pulling: /private/var/mobile/Containers/Bundle/Application/57C5310C-57F7-4583-BC16-0FEA2F5613A6/MCEirectTest.app/Info.plist -> /root/.needle/tmp/plist
[D] Downloading: "/private/var/mobile/Containers/Bundle/Application/57C5310C-57F7-4583-BC16-0FEA2F5613A6/MCEirectTest.app/Info.plist" -> /root/.needle/tmp/plist
[D] [LOCAL CMD] Local Command: sshpass -p "alpine" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 22 root@192.168.100.11:"/private/var/mobile/Containers/Bundle/Application/57C5310C-57F7-4583-BC16-0FEA2F5613A6/MCEirectTest.app/Info.plist" /root/.needle/tmp/plist
[D] [REMOTE CMD] Remote Command: lipo -info /private/var/mobile/Containers/Bundle/Application/57C5310C-57F7-4583-BC16-0FEA2F5613A6/MCEirectTest.app/MCEirectTest
------------------------------------------------------------
Traceback (most recent call last):
  File "/root/needle/needle/core/framework/module.py", line 111, in do_run
    pre = self.module_pre()
  File "/root/needle/needle/core/framework/module.py", line 147, in module_pre
    if self.app_check() is None: return None
  File "/root/needle/needle/core/framework/framework.py", line 665, in app_check
    self.APP_METADATA = Framework.APP_METADATA = self.device.app.get_metadata(app)
  File "/root/needle/needle/core/device/app.py", line 19, in get_metadata
    return self._retrieve_metadata()
  File "/root/needle/needle/core/device/app.py", line 40, in _retrieve_metadata
    architectures = self.__detect_architectures(binary_path)
  File "/root/needle/needle/core/device/app.py", line 111, in __detect_architectures
    out = self._device.remote_op.command_blocking(cmd, internal=True)
  File "/root/needle/needle/core/device/remote_operations.py", line 94, in command_blocking
    out, err = self._device._exec_command_ssh(cmd, internal)
  File "/root/needle/needle/core/device/device.py", line 128, in _exec_command_ssh
    raise Exception(err_str)
Exception: dyld: lazy symbol binding failed: Symbol not found: _map_fd
  Referenced from: /usr/bin/lipo
  Expected in: dyld shared cache

dyld: Symbol not found: _map_fd
  Referenced from: /usr/bin/lipo
  Expected in: dyld shared cache


------------------------------------------------------------
[!]   Expected in: dyld shared cache.
[needle][strings] > 
```

**Comment by marco-lancini** [comment]
Please see https://github.com/mwrlabs/needle/issues/11
