### ISSUE TITLE
can't start needle.py (ImportError)

### ISSUE THREAD

**Issue by rromanen** [mwrlabs/needle#188]
## Issue
Getting an error when I try to launch the needle.py script as so, python needle/needle/needle.py
### Expected behavior
Needle script needs to launch to display script options

### Actual behavior
Receive ImportError: No module named cryptography.hazmat.backends

### needle error logs

$ python needle/needle/needle.py
Traceback (most recent call last):
  File "needle/needle/needle.py", line 9, in <module>
    from core.framework import cli
  File "/Users/roman/needle/needle/core/framework/cli.py", line 10, in <module>
    from framework import Framework, FrameworkException, Mode
  File "/Users/roman/needle/needle/core/framework/framework.py", line 10, in <module>
    from ..device.device import Device
  File "/Users/roman/needle/needle/core/device/device.py", line 2, in <module>
    import paramiko
  File "build/bdist.macosx-10.11-intel/egg/paramiko/__init__.py", line 31, in <module>
  File "build/bdist.macosx-10.11-intel/egg/paramiko/transport.py", line 33, in <module>
ImportError: No module named cryptography.hazmat.backends

#### Needle Version

- Framework (on your machine): latest
- Agent (on your device): 1.0.5

#### Workstation Operating System
Mac OSX El Capitan

#### Python Version
2.7

#### Device iOS Version
iOS 8.3

**Comment by marco-lancini** [comment]
Please refer to the installation guide: https://github.com/mwrlabs/needle/wiki/Installation-Guide
