### ISSUE TITLE
Python script not executing.

### ISSUE THREAD

**Issue by pragyan1994** [mwrlabs/needle#189]
### needle$: sudo -H pip install --upgrade --user biplist
Password:
Requirement already up-to-date: biplist in /private/var/root/Library/Python/2.7/lib/python/site-packages
needle$: python needle.py
Traceback (most recent call last):
  File "needle.py", line 9, in <module>
    from core.framework import cli
  File "/Users/pragyan.a.paramita/Downloads/needle/needle/core/framework/cli.py", line 8, in <module>
    from ..utils.printer import Colors, Printer
  File "/Users/pragyan.a.paramita/Downloads/needle/needle/core/utils/printer.py", line 4, in <module>
    from utils import Utils
  File "/Users/pragyan.a.paramita/Downloads/needle/needle/core/utils/utils.py", line 6, in <module>
    import biplist
ImportError: No module named biplist
needle$: 

### Steps to reproduce
1.install needle
-cd needle

2.python needle.py

###

**Comment by marco-lancini** [comment]
Hi @pragyan1994, somehow biplist is not being installed correctly on your system.
I'll have to close this issue as it is not related to needle.
