### ISSUE TITLE
a lot of modules do not support ios10

### ISSUE THREAD

**Issue by nanshihui** [mwrlabs/needle#197]
a lot of modules do not support ios10,
how to do with it

**Comment by marco-lancini** [comment]
In order to debug this issue, we require more information.

Ensure `VERBOSE` and `DEBUG` mode are enabled, this will provide us with more detailed needle logs:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

Once you have this information, please attach the log files (starting from when you type `python needle.py`) to this thread and we can assist further.

**Comment by olbrichj** [comment]
Here is one output for pull_ipa

```
[needle][pull_ipa] > run
[*] Checking connection with device...
[+] Already connected to: 127.0.0.1
[D] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[!] 'NoneType' object has no attribute 'exec_command'
[V] [SSH] Disconnecting...
[V] [AGENT] Disconnecting from agent...
[D] Stopping USB port forwarding
[D] [LOCAL CMD] Stopping Local Subprocess Command [pid: 38653]
[D] [AGENT] Stopping port forwarding
[?] Resetting connection to device...
[D] Setting up USB port forwarding on port 2222
[D] [LOCAL CMD] Local Subprocess Command: /Users/janolbrich/Downloads/Needle/needle/needle/libs/usbmuxd/tcprelay.py -t 22:2222
[D] [AGENT] Setting up port forwarding on port 4444
[V] [AGENT] Connecting to agent (127.0.0.1:4444)...
[+] [AGENT] Successfully connected to agent (127.0.0.1:4444)...
[D] [AGENT] Executing command: os_version
[V] [SSH] Connecting (127.0.0.1:2222)...
[+] [SSH] Connected (127.0.0.1:2222)
[?] Rerunning last command...
[D] [AGENT] Executing command: os_version
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/janolbrich/Downloads/Needle/needle/needle/core/framework/module.py", line 111, in do_run
    pre = self.module_pre()
  File "/Users/janolbrich/Downloads/Needle/needle/needle/core/framework/module.py", line 143, in module_pre
    raise FrameworkException('This module is not currently supported by the iOS version of the device in use (iOS {})'.format(self.device._ios_version))
FrameworkException: This module is not currently supported by the iOS version of the device in use (iOS 10)
------------------------------------------------------------
[!] FrameworkException: This module is not currently supported by the iOS version of the device in use (iOS 10)
```

**Comment by marco-lancini** [comment]
Hi @nanshihui, this is expected behaviour

**Comment by nanshihui** [comment]
thanks a lot

**Comment by marco-lancini** [comment]
@HenryHoggard I suggest to close this issue

**Comment by HenryHoggard** [comment]
Is this a dependency issue, what is the reason why this module isn't supported on 10?

**Comment by marco-lancini** [comment]
`pull_ipa` relies on `AppSync` which causes a boot loop on iOS 10

**Comment by ArnCo** [comment]
Hi Marco,
I have not been using needle for a while, but I seem to remember that it worked at one point.
Is there any plan to support IOS10 "again" in the near future ?
Cheers.

**Comment by HenryHoggard** [comment]
@ArnCo  iOS 10 should be for the most part supported. If you have issues with any modules then create an issue and we will fix them. In regards to this particular issue Appsync Unified" from https://cydia.angelxwind.net/  is tested and safe to use on iOS 10, so we will commit a fix that allows ipa_installer on iOS 10 when appsync unified is installed.

**Comment by HenryHoggard** [comment]
Renamed issue to more relevant title..
