### ISSUE TITLE
biplist install issue

### ISSUE THREAD

**Issue by 0xff7** [mwrlabs/needle#206]
Any idea how to fix this? I've installed biplist through homebrew. I'm on macOS 10.13.2

`python needle.py
Traceback (most recent call last):
  File "needle.py", line 9, in <module>
    from core.framework import cli
  File "/Users/tim/needle/needle/core/framework/cli.py", line 8, in <module>
    from ..utils.printer import Colors, Printer
  File "/Users/tim/needle/needle/core/utils/printer.py", line 4, in <module>
    from utils import Utils
  File "/Users/tim/needle/needle/core/utils/utils.py", line 6, in <module>
    import biplist
ImportError: No module named biplist`

**Comment by subrosaassociates** [comment]
```sudo easy_install biplist``` should do it

**Comment by 0xff7** [comment]
Had to do the same for sshtunnel but yep that fixed it! Thanks
