### ISSUE TITLE
Keychain Dump 'KeyError' when no applications are installed

### ISSUE THREAD

**Issue by HenryHoggard** [mwrlabs/needle#23]
### Expected behaviour
It should be possible to read the keychain even with no  applications are installed. For example users might want to read the default system keychain.

### Actual behaviour

If no applications are installed, It always asks to choose an application number, if I press enter with no number It shows this error:
```
[+] Apps found:
Please select a number: 
Traceback (most recent call last):
  File "/home/test/Tools/iOS/Needle/needle/core/framework/module.py", line 120, in do_run
    pre = self.module_pre()
  File "/home/test/Tools/iOS/Needle/needle/core/framework/module.py", line 144, in module_pre
    if self.app_check() is None: return None
  File "/home/test/Tools/iOS/Needle/needle/core/framework/framework.py", line 667, in app_check
    app = self.device.select_target_app()
  File "/home/test/Tools/iOS/Needle/needle/core/device/device.py", line 194, in select_target_app
    app_name = choose_from_list(self._applist.keys())
  File "/home/test/Tools/iOS/Needle/needle/core/utils/menu.py", line 18, in choose_from_list
    chosen_val = dict_opts[int(choice)]
ValueError: invalid literal for int() with base 10: ''
------------------------------------------------------------
[!] ValueError: invalid literal for int() with base 10: ''.
```

If I try choose a number that doesn't exist, for example 0, it shows this error:
```
[+] Apps found:
Please select a number: 0
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/Tools/iOS/Needle/needle/core/framework/module.py", line 120, in do_run
    pre = self.module_pre()
  File "/home/test/Tools/iOS/Needle/needle/core/framework/module.py", line 144, in module_pre
    if self.app_check() is None: return None
  File "/home/test/Tools/iOS/Needle/needle/core/framework/framework.py", line 667, in app_check
    app = self.device.select_target_app()
  File "/home/test/Tools/iOS/Needle/needle/core/device/device.py", line 194, in select_target_app
    app_name = choose_from_list(self._applist.keys())
  File "/home/test/Tools/iOS/Needle/needle/core/utils/menu.py", line 18, in choose_from_list
    chosen_val = dict_opts[int(choice)]
KeyError: 0
------------------------------------------------------------
[!] KeyError: 0.
```

### Steps to reproduce

Have device with no extra applications installed

1.` set port 22`
2. `set ip <ip>`
3. `set debug true`
4. `use storage/data/keychain_dump`
5. `run`

#### Workstation Operating System
Debian

#### Python Version
Python 2.7.11

#### Device iOS Version
iOS 9.1

**Comment by marco-lancini** [comment]
hi @HenryHoggard, this should now be fixed in the `develop` branch
