### ISSUE TITLE
Issue connection to agent when running metadata commands on an application

### ISSUE THREAD

**Issue by poldenais** [mwrlabs/needle#247]
## Issue
I can run needle and have the agent installed and show modules works and the list apps on the devices works but when I choose an app in [metadata] it errors on connection again.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
it fails to connect and attempts to connect 3 times.

### Steps to reproduce
1. Needle agent active, run use binary/info/metadata
2. Apps listed-> choose an app
3.error connecting to agent

### needle error logs
```
[?] Resetting connection to device...
[D] Setting up USB port forwarding on port 2222
[D] [LOCAL CMD] Local Subprocess Command: /Users/paulnash/Downloads/needle-master/needle/libs/usbmuxd/tcprelay.py -t 22:2222
[D] [AGENT] Setting up port forwarding on port 4444
[V] [AGENT] Connecting to agent (127.0.0.1:4444)...
[+] [AGENT] Successfully connected to agent (127.0.0.1:4444)...
[D] [AGENT] Executing command: os_version
[V] [SSH] Connecting (127.0.0.1:2222)...
[+] [SSH] Connected (127.0.0.1:2222)
[?] Rerunning last command...
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/paulnash/Downloads/needle-master/needle/core/framework/module.py", line 111, in do_run
    pre = self.module_pre()
  File "/Users/paulnash/Downloads/needle-master/needle/core/framework/module.py", line 147, in module_pre
    if self.app_check() is None: return None
  File "/Users/paulnash/Downloads/needle-master/needle/core/framework/framework.py", line 693, in app_check
    self.APP_METADATA = Framework.APP_METADATA = self.device.app.get_metadata(app)
  File "/Users/paulnash/Downloads/needle-master/needle/core/device/app.py", line 17, in get_metadata
    return self._retrieve_metadata()
  File "/Users/paulnash/Downloads/needle-master/needle/core/device/app.py", line 35, in _retrieve_metadata
    architectures = self.__detect_architectures(binary_path)
  File "/Users/paulnash/Downloads/needle-master/needle/core/device/app.py", line 117, in __detect_architectures
    out = self._device.remote_op.command_blocking(cmd, internal=True)
  File "/Users/paulnash/Downloads/needle-master/needle/core/device/remote_operations.py", line 94, in command_blocking
    out, err = self._device._exec_command_ssh(cmd, internal)
  File "/Users/paulnash/Downloads/needle-master/needle/core/utils/utils.py", line 211, in wrapper
    raise Exception("An error occurred and it was not possible to restore it ({} attempts failed)".format(self.tries))
Exception: An error occurred and it was not possible to restore it (3 attempts failed)
------------------------------------------------------------
[!] Exception: An error occurred and it was not possible to restore it (3 attempts failed)
[needle][metadata] > 
```

#### Needle Version

- Framework v1.3.2
- Agent v1.0.5

#### Workstation Operating System
macbook

#### Python Version
2.7

#### Device iOS Version
10.2

**Comment by poldenais** [comment]
installed Darwin CC tools to fix this. had it on before and didn't realise it was removed.
