### ISSUE TITLE
ImportError: No module named biplist

### ISSUE THREAD

**Issue by omkarparth** [mwrlabs/needle#253]
## Issue
Even after following the installation guide for Mac OS and downloading/installing all the dependencies/requirements the needle python file does not execute.

### Actual behaviour
I am getting the following error:
$ python needle.py
Traceback (most recent call last):
  File "needle.py", line 9, in <module>
    from core.framework import cli
  File "/Users/ADMParkhe/needle/needle/core/framework/cli.py", line 8, in <module>
    from ..utils.printer import Colors, Printer
  File "/Users/ADMParkhe/needle/needle/core/utils/printer.py", line 4, in <module>
    from utils import Utils
  File "/Users/ADMParkhe/needle/needle/core/utils/utils.py", line 6, in <module>
    import biplist
ImportError: No module named biplist

####Note 
I have tried sudo -H pip install --upgrade --user biplist  and sudo easy_install biplist which says that biplist 1.0.3 is already the active version in easy-install.pth.

#### Needle Version
- Agent (on your device): 1.0.5

#### Workstation Operating System
Mac OS

#### Python Version
Python 2.7.15

#### Device iOS Version
10.2

**Comment by Yogehi** [comment]
hello,

if you ran `sudo -H pip install --upgrade --user biplist` to install `biplist` then you may need to run `sudo -H python ./needle.py` to run needle.

**Comment by VirenMohindra** [comment]
@Yogehi `sudo` didn't change anything.

output

```
laptop$ sudo -H python ./needle.py
Traceback (most recent call last):
  File "./needle.py", line 9, in <module>
    from core.framework import cli
  File "/Users/virenmohindra/Desktop/Neat/Mobile Network Analysis/needle/needle/core/framework/cli.py", line 8, in <module>
    from ..utils.printer import Colors, Printer
  File "/Users/virenmohindra/Desktop/Neat/Mobile Network Analysis/needle/needle/core/utils/printer.py", line 4, in <module>
    from utils import Utils
  File "/Users/virenmohindra/Desktop/Neat/Mobile Network Analysis/needle/needle/core/utils/utils.py", line 6, in <module>
    import biplist
ImportError: No module named biplist
```

**Comment by omkarparth** [comment]
It worked for me. Thanks :)

**Comment by VirenMohindra** [comment]
easy_install for other components worked for me. pip was being cumbersome for some reason.

**Comment by 0xVIC** [comment]
Same error in MacOSX and Kali Linux.
easy_install no work. I have tried all the answers in the many biplist issues.
