### ISSUE TITLE
[!] HandlerSSHTunnelForwarderError: An error occurred while opening tunnels.

### ISSUE THREAD

**Issue by humanUnit** [mwrlabs/needle#264]
## Issue

Hi Marco, could you please help me? This issue happens if I used needle for some time, and then exit it and reconnect back. Needle Agent is running.

### Steps to reproduce
1. Start needle > sudo python needle.py
2. Enter password.

### needle error logs
```
[needle] > set AGENT_PORT 4444
AGENT_PORT => 4444
[needle] > set DEBUG True
DEBUG => True
[needle] > set HIDE_SYSTEM_APPS False
HIDE_SYSTEM_APPS => False
[needle] > set IP 127.0.0.1
IP => 127.0.0.1
[needle] > set PORT 2222
PORT => 2222
[needle] > set OUTPUT_FOLDER /Users/mehadhe_sameer/needle/needle/output
OUTPUT_FOLDER => /Users/mehadhe_sameer/needle/needle/output
[D] Output folder changed, reloading modules
[needle] > set PASSWORD 
PASSWORD => ********
[needle] > set SKIP_OUTPUT_FOLDER_CHECK True
SKIP_OUTPUT_FOLDER_CHECK => True
[needle] > set USERNAME root
USERNAME => root
[needle] > set VERBOSE True
VERBOSE => True
[needle] > use storage/caching/screenshot
[needle][screenshot] > run
[D] Setup local output folder: /Users/mehadhe_sameer/needle/needle/output
[D] Setting up issues database...
[D] [DB] QUERY: CREATE TABLE IF NOT EXISTS issues (app TEXT, module TEXT, name TEXT, content TEXT, confidence TEXT, outfile TEXT)
[*] Checking connection with device...
[V] Connection not present, creating a new instance
[D] Setting up USB port forwarding on port 2222
[D] [LOCAL CMD] Local Subprocess Command: /Users/ekaterinak/needle/needle/libs/usbmuxd/tcprelay.py -t 22:2222
[D] [AGENT] Setting up port forwarding on port 4444
2018-10-10 17:01:13,415| ERROR   | Problem setting SSH Forwarder up: Couldn't open tunnel 127.0.0.1:4444 <> 127.0.0.1:4444 might be in use or destination not reachable
[!] Problem establishing connection: HandlerSSHTunnelForwarderError -  
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ekaterinak/needle/needle/core/framework/framework.py", line 641, in _connection_new
    self.device.connect()
  File "/Users/ekaterinak/needle/needle/core/device/device.py", line 216, in connect
    self._portforward_agent_start()
  File "/Users/ekaterinak/needle/needle/core/device/device.py", line 149, in _portforward_agent_start
    self._port_forward_agent.start()
  File "/Users/ekaterinak/Library/Python/2.7/lib/python/site-packages/sshtunnel.py", line 1308, in start
    'An error occurred while opening tunnels.')
  File "/Users/ekaterinak/Library/Python/2.7/lib/python/site-packages/sshtunnel.py", line 1101, in _raise
    raise exception(reason)
HandlerSSHTunnelForwarderError: An error occurred while opening tunnels.
------------------------------------------------------------
[!] HandlerSSHTunnelForwarderError: An error occurred while opening tunnels.
[V] [SSH] Disconnecting...
[D] Stopping USB port forwarding
[D] [LOCAL CMD] Stopping Local Subprocess Command [pid: 3036]
[D] [AGENT] Stopping port forwarding
```

#### Needle Version
Needle v1.3.2 [mwr.to/needle]  
- Framework (on your machine): 
- Agent (on your device): Cydia

#### Workstation Operating System
macOS Mojave 10.14

#### Python Version
2.7, but 3.2 doesn't work at all.

#### Python Packages (`pip freeze`)
asn1crypto==0.24.0
bcrypt==3.1.4
biplist==1.0.3
cffi==1.11.5
cryptography==2.3.1
enum34==1.1.6
frida==12.2.11
gnureadline==6.3.8
idna==2.7
ipaddress==1.0.22
paramiko==2.4.2
pyasn1==0.4.4
pycparser==2.19
PyNaCl==1.3.0
six==1.11.0
sshtunnel==0.1.4

#### Device iOS Version
 Iphone 5 IOS 10.3.3

**Comment by marco-lancini** [comment]
Hi @humanUnit, probably something hasn't been exited gracefully. This might leave the port forwarding running in background (hence why is now failing to re-start the forwarding on the same port `4444`).

Try to gracefully exit both needle and the agent, and ensure no background processes are left running.
To test this theory you can also try use different ports.

Feel free to reopen this issue if the problem still persists.
