### ISSUE TITLE
Exception:PID not found

### ISSUE THREAD

**Issue by ankushgoel27** [mwrlabs/needle#43]
### Expected behaviour
Cycript should be able to find the PID and attach to the process. i can see the PID and the process when i run this command on the device - 'ps ax | grep - i 'whasome.app'' which shows all the running processes.

###Actual Behaviour
I have an app installed that checks for jailbroken device and throws an error on the screen within the app that it cannot run because the device is jailbroken. I am trying to attach the cycript and frida module however they throw an error saying that the PID is not found after the app is launched on the device. The app does not exits after the error.

### Steps to reproduce
1.use hooking/cycript/cycript
2.
3.

### needle error logs
Ensure verbose and debug mode are enabled:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

## Environment
Kali Linux/VMWARE
#### Workstation Operating System
Kali Linux
#### Python Version
python 2.7
#### Python Packages (`pip freeze`)
i have a huge list
#### Device iOS Version
IPAD IOS 9.3.3

**Comment by marco-lancini** [comment]
Hi @ankushgoel27, a couple of comments:

1) In "Steps to reproduce" you list a non-existent module `hooking/cycript/cycript`. I assume you are referring to `hooking/cycript/cycript_shell`?
2) Can you please post also `verbose` and `debug` logs please?

**Comment by ankushgoel27** [comment]
[needle][script_enum-classes] > run
[*] Checking connection with device...
[+] Already connected to: 192.168.0.6
[V] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[+] Target app: com.westernhealth.whasome
[*] Local port forwarding to enable communications with the Frida server already setup
[D] Connected over Wi-Fi
[*] Launching the app...
[D] [REMOTE CMD] Remote Command: open com.westernhealth.whasome
[V] Retrieving the PID...
[D] [REMOTE CMD] Remote Command: ps ax | grep -i 'whasome.app'
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/needle/needle/core/framework/module.py", line 111, in do_run
    pre = self.module_pre()
  File "/opt/needle/needle/core/framework/module.py", line 267, in module_pre
    pid = int(self.device.app.search_pid(self.APP_METADATA['name']))
  File "/opt/needle/needle/core/device/app.py", line 176, in search_pid
    raise Exception("PID not found")
Exception: PID not found
------------------------------------------------------------
[!] Exception: PID not found.

**Comment by ankushgoel27** [comment]
Ankush-Goels-iPad:~ root# ps ax | grep -i "whasome"
 2984   ??  Ss     0:01.26 /var/containers/Bundle/Application/E2E45BB2-8A4A-4CB9-A70F-E89419D767F4/whasome.app/whasome
 3061 s000  R+     0:00.00 grep -i whasome

**Comment by ankushgoel27** [comment]
Ankush-Goels-iPad:~ root# ps ax | grep -i "whasome.app"
 2984   ??  Ss     0:01.26 /var/containers/Bundle/Application/E2E45BB2-8A4A-4CB9-A70F-E89419D767F4/whasome.app/whasome
 3063 s000  R+     0:00.00 grep -i whasome.app

**Comment by marco-lancini** [comment]
ok thanks for the info, could you try to download the latest version of needle (updated just now) and try again?

**Comment by ankushgoel27** [comment]
yup, it works fine now.

Thanks,

**Comment by illnino** [comment]
## Description

[!] Exception: PID not found

## ENV

Mac OS 10.11.6
iPhone OS 9.0
Python 2.7
Needle Agent 1.0.3

Needle 
```
commit 013950d1f18a60e789a2bc84d17a3fc10eaedd32
Author: Marco Lancini <info@marcolancini.it>
Date:   Fri May 5 09:11:03 2017 +0100

    [V1.1.0] Update version and changelog
```


## Reproduction Steps

```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
[needle] > use hooking/cycript/cycript_shell
[needle][cycript_shell] > run
[*] Checking connection with device...
[+] Already connected to: 127.0.0.1
[D] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[!] SSH Session appears to have died!
[V] [SSH] Disconnecting...
[V] [AGENT] Disconnecting from agent...
[D] Stopping USB port forwarding
[D] [LOCAL CMD] Stopping Local Subprocess Command [pid: 93270]
[D] [AGENT] Stopping port forwarding
[?] Reconnecting to device...
[D] Setting up USB port forwarding on port 2222
[D] [LOCAL CMD] Local Subprocess Command: /Users/its/Project/tools/iOS/needle/needle/libs/usbmuxd/tcprelay.py -t 22:2222
[D] [AGENT] Setting up port forwarding on port 4444
[V] [AGENT] Connecting to agent (127.0.0.1:4444)...
[+] [AGENT] Successfully connected to agent (127.0.0.1:4444)...
[D] [AGENT] Executing command: os_version
[D] [AGENT] Parsing result
[V] [SSH] Connecting (127.0.0.1:2222)...
[+] [SSH] Connected (127.0.0.1:2222)
[?] Rerunning last command...
[+] Target app: com.[redacted]
[*] Launching the app...
[D] [REMOTE CMD] Remote Command: open com.[redacted]
[V] Retrieving the PID...
[D] [REMOTE CMD] Remote Command: ps ax | grep -i '[redacted]'
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/its/Project/tools/iOS/needle/needle/core/framework/module.py", line 117, in do_run
    self.module_run()
  File "/Users/its/Project/tools/iOS/needle/needle/modules/hooking/cycript/cycript_shell.py", line 21, in module_run
    pid = self.device.app.search_pid(self.APP_METADATA['name'])
  File "/Users/its/Project/tools/iOS/needle/needle/core/device/app.py", line 184, in search_pid
    raise Exception("PID not found")
Exception: PID not found
------------------------------------------------------------
[!] Exception: PID not found
[needle][cycript_shell] >
```

**Comment by marco-lancini** [comment]
Hi, could you try the latest version from the `develop` branch please?

**Comment by illnino** [comment]
No Luck

```
$  needle git:(develop) ✗ python needle.py

             __   _ _______ _______ ______         _______
             | \  | |______ |______ |     \ |      |______
             |  \_| |______ |______ |_____/ |_____ |______

                   Needle v1.2.0 [mwr.to/needle]
  [MWR InfoSecurity (@MWRLabs) - Marco Lancini (@LanciniMarco)]

[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
[needle] > use hooking/cycript/cycript_shell
[needle][cycript_shell] > run
[D] Setup local output folder: /Users/its/.needle/output
[?] Attention! The folder chosen to store local output is not empty: /Users/its/.needle/output
[?] Do you want to back it up first?
[?] Y: the content will be archived in a different location, then the folder will be emptied
[?] N: no action will be taken (destination files might be overwritten in case of filename clash)
[y/n]: y
[V] Archiving local output folder: /Users/its/.needle/output --> /Users/its/.needle/backup/needle-output_2017-05-23-17:01:14
[D] Copying: /Users/its/.needle/output -> /Users/its/.needle/backup/needle-output_2017-05-23-17:01:14
[D] Deleting: /Users/its/.needle/output
[D] Creating local output folder: /Users/its/.needle/output
[D] Setting up issue's database...
[D] [DB] QUERY: CREATE TABLE IF NOT EXISTS issues (app TEXT, module TEXT, name TEXT, content TEXT, confidence TEXT, outfile TEXT)
[D] Setting up issue's database...
[D] [DB] QUERY: CREATE TABLE IF NOT EXISTS issues (app TEXT, module TEXT, name TEXT, content TEXT, confidence TEXT, outfile TEXT)
[*] Checking connection with device...
[V] Connection not present, creating a new instance
[D] Setting up USB port forwarding on port 2222
[D] [LOCAL CMD] Local Subprocess Command: /Users/its/Project/tools/iOS/needle/needle/libs/usbmuxd/tcprelay.py -t 22:2222
[D] [AGENT] Setting up port forwarding on port 4444
[V] [AGENT] Connecting to agent (127.0.0.1:4444)...
[+] [AGENT] Successfully connected to agent (127.0.0.1:4444)...
[D] [AGENT] Executing command: os_version
[D] [AGENT] Parsing result (are you sure the agent is in the foreground?)
[!] [Errno 9] Bad file descriptor
[V] [SSH] Disconnecting...
[V] [AGENT] Disconnecting from agent...
[D] Stopping USB port forwarding
[D] [LOCAL CMD] Stopping Local Subprocess Command [pid: 95653]
[D] [AGENT] Stopping port forwarding
2017-05-23 17:01:16,573| ERROR   | Could not establish connection from ('127.0.0.1', 4444) to remote side of the tunnel
[?] Resetting connection to device...
[D] Setting up USB port forwarding on port 2222
[D] [LOCAL CMD] Local Subprocess Command: /Users/its/Project/tools/iOS/needle/needle/libs/usbmuxd/tcprelay.py -t 22:2222
[D] [AGENT] Setting up port forwarding on port 4444
[V] [AGENT] Connecting to agent (127.0.0.1:4444)...
[+] [AGENT] Successfully connected to agent (127.0.0.1:4444)...
[D] [AGENT] Executing command: os_version
[D] [AGENT] Parsing result (are you sure the agent is in the foreground?)
[!] [Errno 9] Bad file descriptor
[V] [SSH] Disconnecting...
[V] [AGENT] Disconnecting from agent...
[D] Stopping USB port forwarding
[D] [LOCAL CMD] Stopping Local Subprocess Command [pid: 95654]
[D] [AGENT] Stopping port forwarding
[?] Resetting connection to device...
[D] Setting up USB port forwarding on port 2222
[D] [LOCAL CMD] Local Subprocess Command: /Users/its/Project/tools/iOS/needle/needle/libs/usbmuxd/tcprelay.py -t 22:2222
2017-05-23 17:01:19,058| ERROR   | Could not establish connection from ('127.0.0.1', 4444) to remote side of the tunnel
[D] [AGENT] Setting up port forwarding on port 4444
[V] [AGENT] Connecting to agent (127.0.0.1:4444)...
[+] [AGENT] Successfully connected to agent (127.0.0.1:4444)...
[D] [AGENT] Executing command: os_version
[D] [AGENT] Parsing result (are you sure the agent is in the foreground?)
[V] [SSH] Connecting (127.0.0.1:2222)...
[+] [SSH] Connected (127.0.0.1:2222)
[?] Rerunning last command...
[D] [AGENT] Executing command: os_version
[D] [AGENT] Parsing result (are you sure the agent is in the foreground?)
[V] [SSH] Connecting (127.0.0.1:2222)...
[+] [SSH] Connected (127.0.0.1:2222)
[?] Rerunning last command...
[D] [AGENT] Executing command: os_version
[D] [AGENT] Parsing result (are you sure the agent is in the foreground?)
[V] [SSH] Connecting (127.0.0.1:2222)...
[+] [SSH] Connected (127.0.0.1:2222)
[D] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: mkdir /var/root/needle/
[D] [AGENT] Executing command: os_version
[D] [AGENT] Parsing result (are you sure the agent is in the foreground?)
[*] Target app not selected. Launching wizard...
[D] [AGENT] Executing command: list_apps
[D] [AGENT] Parsing result (are you sure the agent is in the foreground?)
[+] Apps found:
		0 - com.liguangming.Shadowrocket
		[redacted]

[>][QUESTION] Please select a number: 9
[+] Target app: com.[redacted]
[*] Retrieving app's metadata...
[D] Copying the plist to temp: /private/var/mobile/Containers/Bundle/Application/B8C4E507-1C20-4190-AE3E-075B97AE2565/[redacted].app/Info.plist -> /Users/its/.needle/tmp/plist
[*] Pulling: /private/var/mobile/Containers/Bundle/Application/B8C4E507-1C20-4190-AE3E-075B97AE2565/[redacted].app/Info.plist -> /Users/its/.needle/tmp/plist
[D] Downloading: "/private/var/mobile/Containers/Bundle/Application/B8C4E507-1C20-4190-AE3E-075B97AE2565/[redacted].app/Info.plist" -> /Users/its/.needle/tmp/plist
[D] [LOCAL CMD] Local Command: sshpass -p "alpine" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 2222 root@127.0.0.1:"/private/var/mobile/Containers/Bundle/Application/B8C4E507-1C20-4190-AE3E-075B97AE2565/[redacted].app/Info.plist" /Users/its/.needle/tmp/plist
[D] [REMOTE CMD] Remote Command: lipo -info /private/var/mobile/Containers/Bundle/Application/B8C4E507-1C20-4190-AE3E-075B97AE2565/[redacted].app/[redacted]
[D] [REMOTE CMD] Remote Command: if [ -d /private/var/mobile/Containers/Bundle/Application/B8C4E507-1C20-4190-AE3E-075B97AE2565/[redacted].app/PlugIns ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: if [ -d /private/var/mobile/Containers/Bundle/Application/B8C4E507-1C20-4190-AE3E-075B97AE2565/[redacted].app/PlugIns ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: ls  /private/var/mobile/Containers/Bundle/Application/B8C4E507-1C20-4190-AE3E-075B97AE2565/[redacted].app/PlugIns
[D] Copying the plist to temp: /private/var/mobile/Containers/Bundle/Application/B8C4E507-1C20-4190-AE3E-075B97AE2565/[redacted].app/PlugIns/SiriPaymentIntent.appex/Info.plist -> /Users/its/.needle/tmp/plist
[*] Pulling: /private/var/mobile/Containers/Bundle/Application/B8C4E507-1C20-4190-AE3E-075B97AE2565/[redacted].app/PlugIns/SiriPaymentIntent.appex/Info.plist -> /Users/its/.needle/tmp/plist
[D] Downloading: "/private/var/mobile/Containers/Bundle/Application/B8C4E507-1C20-4190-AE3E-075B97AE2565/[redacted].app/PlugIns/SiriPaymentIntent.appex/Info.plist" -> /Users/its/.needle/tmp/plist
[D] [LOCAL CMD] Local Command: sshpass -p "alpine" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 2222 root@127.0.0.1:"/private/var/mobile/Containers/Bundle/Application/B8C4E507-1C20-4190-AE3E-075B97AE2565/[redacted].app/PlugIns/SiriPaymentIntent.appex/Info.plist" /Users/its/.needle/tmp/plist
[D] Copying the plist to temp: /private/var/mobile/Containers/Bundle/Application/B8C4E507-1C20-4190-AE3E-075B97AE2565/[redacted].app/PlugIns/SiriUI.appex/Info.plist -> /Users/its/.needle/tmp/plist
[*] Pulling: /private/var/mobile/Containers/Bundle/Application/B8C4E507-1C20-4190-AE3E-075B97AE2565/[redacted].app/PlugIns/SiriUI.appex/Info.plist -> /Users/its/.needle/tmp/plist
[D] Downloading: "/private/var/mobile/Containers/Bundle/Application/B8C4E507-1C20-4190-AE3E-075B97AE2565/[redacted].app/PlugIns/SiriUI.appex/Info.plist" -> /Users/its/.needle/tmp/plist
[D] [LOCAL CMD] Local Command: sshpass -p "alpine" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 2222 root@127.0.0.1:"/private/var/mobile/Containers/Bundle/Application/B8C4E507-1C20-4190-AE3E-075B97AE2565/[redacted].app/PlugIns/SiriUI.appex/Info.plist" /Users/its/.needle/tmp/plist
[*] Launching the app...
[D] [REMOTE CMD] Remote Command: open com.[redacted]
[V] Retrieving the PID...
[D] [REMOTE CMD] Remote Command: ps ax | grep -i '[redacted]'
[V] PID found: 764
[*] Spawning a Cycript shell...
[D] [REMOTE CMD] Remote Interactive TTY Command: cycript -p 764
Warning: Permanently added '[127.0.0.1]:2222' (RSA) to the list of known hosts.

```

**Comment by marco-lancini** [comment]
can you run other modules successfully?

**Comment by illnino** [comment]
## frida_trace - YES

```
[needle] > use hooking/frida/frida_trace
[needle][frida_trace] > info

      Name: Frida Trace
      Path: modules/hooking/frida/frida_trace.py
    Author: @LanciniMarco (@MWRLabs)

Description:
  Trace the specified functions using frida-trace

Options:
  Name       Current Value  Required  Description
  ---------  -------------  --------  -----------
  FUNCTIONS  False          no        Comma separated list of functions to trace (Example: send*,recv*,CCCryptorCreate*)
  METHODS    False          no        Comma separated list of Objective-C methods to trace (Example: -[NSView drawRect:])
  MODULES    False          no        Comma separated list of modules to trace (Example: libcommonCrypto*)

[needle][frida_trace] > set FUNCTIONS send*
FUNCTIONS => send*
[needle][frida_trace] > run
[?] Attention! The folder chosen to store local output is not empty: /Users/its/.needle/output
[?] Do you want to back it up first?
[?] Y: the content will be archived in a different location, then the folder will be emptied
[?] N: no action will be taken (destination files might be overwritten in case of filename clash)
[y/n]: y
[V] Archiving local output folder: /Users/its/.needle/output --> /Users/its/.needle/backup/needle-output_2017-05-23-18:34:28
[*] Checking connection with device...
[V] Connection not present, creating a new instance
[V] [AGENT] Connecting to agent (127.0.0.1:4444)...
[+] [AGENT] Successfully connected to agent (127.0.0.1:4444)...
[V] [SSH] Connecting (127.0.0.1:2222)...
[+] [SSH] Connected (127.0.0.1:2222)
[*] Target app not selected. Launching wizard...
[+] Apps found:
		0 - com.liguangming.Shadowrocket
		[redacted]
		42 - com.baidu.inputMethod
[>][QUESTION] Please select a number: 10
[+] Target app: com.enchantedcloud.photovault
[*] Retrieving app's metadata...
[*] Pulling: /private/var/mobile/Containers/Bundle/Application/A59C9198-B3EA-4840-94A4-A613A68C2243/PhotoVault.app/Info.plist -> /Users/its/.needle/tmp/plist
[*] Pulling: /private/var/mobile/Containers/Bundle/Application/A59C9198-B3EA-4840-94A4-A613A68C2243/PhotoVault.app/PlugIns/ImportExtension.appex/Info.plist -> /Users/its/.needle/tmp/plist
[*] Setting up local port forwarding to enable communications with the Frida server...
[*] Starting frida-trace...
Instrumenting functions...
send: Auto-generated handler at "/Users/its/Project/tools/iOS/needle/needle/__handlers__/libsystem_c.dylib/send.js"
sendmsg$NOCANCEL: Auto-generated handler at "/Users/its/Project/tools/iOS/needle/needle/__handlers__/libsystem_kernel.dylib/sendmsg_NOCANCEL.js"
sendfile: Auto-generated handler at "/Users/its/Project/tools/iOS/needle/needle/__handlers__/libsystem_kernel.dylib/sendfile.js"
sendmsg: Auto-generated handler at "/Users/its/Project/tools/iOS/needle/needle/__handlers__/libsystem_kernel.dylib/sendmsg.js"
sendmsg_x: Auto-generated handler at "/Users/its/Project/tools/iOS/needle/needle/__handlers__/libsystem_kernel.dylib/sendmsg_x.js"
sendto: Auto-generated handler at "/Users/its/Project/tools/iOS/needle/needle/__handlers__/libsystem_kernel.dylib/sendto.js"
sendto$NOCANCEL: Auto-generated handler at "/Users/its/Project/tools/iOS/needle/needle/__handlers__/libsystem_kernel.dylib/sendto_NOCANCEL.js"
send$NOCANCEL: Auto-generated handler at "/Users/its/Project/tools/iOS/needle/needle/__handlers__/libsystem_c.dylib/send_NOCANCEL.js"
Started tracing 8 functions. Press Ctrl+C to stop.
           /* TID 0x1907 */
   968 ms  send$NOCANCEL()
   968 ms     | sendto$NOCANCEL()
   969 ms  send$NOCANCEL()
   969 ms     | sendto$NOCANCEL()
   969 ms  sendmsg$NOCANCEL()
   978 ms  send$NOCANCEL()
   978 ms     | sendto$NOCANCEL()
   979 ms  send$NOCANCEL()
   979 ms     | sendto$NOCANCEL()
   979 ms  sendmsg$NOCANCEL()
  1063 ms  send$NOCANCEL()
  1063 ms     | sendto$NOCANCEL()
  1064 ms  send$NOCANCEL()
  1064 ms     | sendto$NOCANCEL()
  1064 ms  sendmsg$NOCANCEL()
           /* TID 0x7403 */
  1068 ms  send$NOCANCEL()
  1068 ms     | sendto$NOCANCEL()
           /* TID 0x2403 */
  1068 ms  send$NOCANCEL()
  1068 ms     | sendto$NOCANCEL()
           /* TID 0x9d07 */
  1070 ms  send$NOCANCEL()
  1070 ms     | sendto$NOCANCEL()
           /* TID 0x7403 */
  1070 ms  send$NOCANCEL()
  1070 ms     | sendto$NOCANCEL()
           /* TID 0x2403 */
  1070 ms  send$NOCANCEL()
  1070 ms     | sendto$NOCANCEL()
           /* TID 0x9d07 */
  1070 ms  send$NOCANCEL()
  1071 ms     | sendto$NOCANCEL()
           /* TID 0x7403 */
  1071 ms  sendmsg$NOCANCEL()
           /* TID 0x2403 */
  1071 ms  sendmsg$NOCANCEL()
           /* TID 0x9d07 */
  1071 ms  sendmsg$NOCANCEL()
           /* TID 0x1907 */
  1071 ms  send$NOCANCEL()
  1071 ms     | sendto$NOCANCEL()
  1071 ms  send$NOCANCEL()
  1071 ms     | sendto$NOCANCEL()
  1071 ms  sendmsg$NOCANCEL()
           /* TID 0x9d07 */
  1183 ms  send()
  1183 ms     | sendto()
  1183 ms  send()
  1183 ms     | sendto()
  1183 ms  send()
  1183 ms     | sendto()
           /* TID 0x2403 */
  1199 ms  send()
  1199 ms     | sendto()
  1199 ms  send()
  1199 ms     | sendto()
  1199 ms  send()
  1199 ms     | sendto()
           /* TID 0x9d07 */
  
```


## Screenshot - NO

```
[needle] > use storage/caching/screenshot
[needle][screenshot] > run
[?] Attention! The folder chosen to store local output is not empty: /Users/its/.needle/output
[?] Do you want to back it up first?
[?] Y: the content will be archived in a different location, then the folder will be emptied
[?] N: no action will be taken (destination files might be overwritten in case of filename clash)
[y/n]: y
[V] Archiving local output folder: /Users/its/.needle/output --> /Users/its/.needle/backup/needle-output_2017-05-23-18:32:53
[*] Checking connection with device...
[V] Connection not present, creating a new instance
[V] [AGENT] Connecting to agent (127.0.0.1:4444)...
[+] [AGENT] Successfully connected to agent (127.0.0.1:4444)...
[!] [Errno 9] Bad file descriptor
[V] [SSH] Disconnecting...
[V] [AGENT] Disconnecting from agent...
2017-05-23 18:32:55,877| ERROR   | Could not establish connection from ('127.0.0.1', 4444) to remote side of the tunnel
[?] Resetting connection to device...
[V] [AGENT] Connecting to agent (127.0.0.1:4444)...
[+] [AGENT] Successfully connected to agent (127.0.0.1:4444)...
[!] [Errno 9] Bad file descriptor
[V] [SSH] Disconnecting...
[V] [AGENT] Disconnecting from agent...
[?] Resetting connection to device...
[V] [AGENT] Connecting to agent (127.0.0.1:4444)...
[+] [AGENT] Successfully connected to agent (127.0.0.1:4444)...
[!] [Errno 9] Bad file descriptor
[V] [SSH] Disconnecting...
[V] [AGENT] Disconnecting from agent...
[?] Resetting connection to device...
[V] [AGENT] Connecting to agent (127.0.0.1:4444)...
[+] [AGENT] Successfully connected to agent (127.0.0.1:4444)...
[!] Problem establishing connection: Exception - An error occurred and it was not possible to restore it (3 attempts failed)
[!] Exception: An error occurred and it was not possible to restore it (3 attempts failed)
[V] [SSH] Disconnecting...
[V] [AGENT] Disconnecting from agent...
2017-05-23 18:33:02,894| ERROR   | Could not establish connection from ('127.0.0.1', 4444) to remote side of the tunnel
[needle][screenshot] > run
[*] Checking connection with device...
[V] Connection not present, creating a new instance
[V] [AGENT] Connecting to agent (127.0.0.1:4444)...
[+] [AGENT] Successfully connected to agent (127.0.0.1:4444)...
[!] [Errno 9] Bad file descriptor
[V] [SSH] Disconnecting...
[V] [AGENT] Disconnecting from agent...
[?] Resetting connection to device...
[V] [AGENT] Connecting to agent (127.0.0.1:4444)...
[+] [AGENT] Successfully connected to agent (127.0.0.1:4444)...
[!] [Errno 9] Bad file descriptor
[V] [SSH] Disconnecting...
[V] [AGENT] Disconnecting from agent...
2017-05-23 18:33:17,860| ERROR   | Could not establish connection from ('127.0.0.1', 4444) to remote side of the tunnel
[?] Resetting connection to device...
[V] [AGENT] Connecting to agent (127.0.0.1:4444)...
[+] [AGENT] Successfully connected to agent (127.0.0.1:4444)...
[!] [Errno 9] Bad file descriptor
[V] [SSH] Disconnecting...
[V] [AGENT] Disconnecting from agent...
[?] Resetting connection to device...
[V] [AGENT] Connecting to agent (127.0.0.1:4444)...
[+] [AGENT] Successfully connected to agent (127.0.0.1:4444)...
[!] Problem establishing connection: Exception - An error occurred and it was not possible to restore it (3 attempts failed)
[!] Exception: An error occurred and it was not possible to restore it (3 attempts failed)
[V] [SSH] Disconnecting...
[V] [AGENT] Disconnecting from agent...
2017-05-23 18:33:22,562| ERROR   | Could not establish connection from ('127.0.0.1', 4444) to remote side of the tunnel
[needle][screenshot] >
[needle] >
[needle] > exit
```

**Comment by marco-lancini** [comment]
seems related to #161

**Comment by illnino** [comment]
You are right. `[Errno 9] Bad file descriptor` happens from time to time.
