### ISSUE TITLE
Binary/Metadata Doesn't work if CFBundleDisplayName is not set

### ISSUE THREAD

**Issue by HenryHoggard** [mwrlabs/needle#92]
## Issue

Note: Pathnames and application names have been obscured or modified. 

### Expected behaviour

Binary/metadata module should return parsed plist entries.

### Actual behaviour

If the plist attribute `CFBundleDisplayName` is not set, the module `binary/metadata` will not work.

### Steps to reproduce
1. Download application from App Store that doesn't have CFBundleDisplayName set in plist.
2. `use binary/metadata`
3. `run`

### needle error logs

```
[needle] > use binary/metadata
[needle][metadata] > run
[*] Checking connection with device...
[+] Already connected to: 192.168.137.12
[V] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[+] Target app: com.hh.iosvuln
[*] Retrieving app's metadata...
[D] Copy the plist to temp: '/private/var/mobile/Containers/Bundle/Application/EFC8307D-8F4C-44E9-9F8A-E6AC55D28262/iOS Vuln.app/Info.plist' -> /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cp '/private/var/mobile/Containers/Bundle/Application/EFC8307D-8F4C-44E9-9F8A-E6AC55D28262/iOS Vuln.app/Info.plist' /var/root/needle/Info.plist
[D] Converting plist to XML: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/Info.plist
[D] Extracting content from: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/Info.plist
[D] Parsing plist content
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/h/Tools/iOS/needle-live/needle/core/framework/module.py", line 112, in do_run
    pre = self.module_pre()
  File "/home/h/Tools/iOS/needle-live/needle/core/framework/module.py", line 144, in module_pre
    if self.app_check() is None: return None
  File "/home/h/Tools/iOS/needle-live/needle/core/framework/framework.py", line 692, in app_check
    self.APP_METADATA = Framework.APP_METADATA = self.device.app.get_metadata(app)
  File "/home/h/Tools/iOS/needle-live/needle/core/device/app.py", line 20, in get_metadata
    return self._retrieve_metadata()
  File "/home/h/Tools/iOS/needle-live/needle/core/device/app.py", line 33, in _retrieve_metadata
    metadata_info = self.__parse_plist_info(plist_info)
  File "/home/h/Tools/iOS/needle-live/needle/core/device/app.py", line 84, in __parse_plist_info
    bundle_displayname = plist['CFBundleDisplayName']
KeyError: 'CFBundleDisplayName'
------------------------------------------------------------
[!] KeyError: 'CFBundleDisplayName'.
```

#### Workstation Operating System

Debian

#### Python Version

2.7

#### Device iOS Version

9.3

**Comment by marco-lancini** [comment]
Hi @HenryHoggard, I pushed a more global fix for this issue (which might cover even other atrributes). Could you please test if it works as expected? It has been pushed to `develop` now

**Comment by HenryHoggard** [comment]
Just tested and it works.
